import Head from "next/head";
import Image from "next/image";
import logo from "../assets/logo.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div className="logo__container">
          <figure>
            <Image className="header__logo-img" height={60} src={logo} />
          </figure>
          <span className="header__name">OSMAN CAKIR</span>
        </div>
        <div className="nav__links--container">
          <ul className="nav__links">
            <li className="nav__link">
              <a href="/">Home</a>
            </li>
            <li className="nav__link">
              <a href="/#about">About</a>
            </li>
            <li className="nav__link">
              <a href="">Projects</a>
            </li>
            <li className="nav__link">
              <a href="">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
      <main>
        <section id="landing">
          <div className="container">
            <div className="row">
              <div className="landing__text--container">
                <h1 className="landing__title">HEY, I'M OSMAN CAKIR</h1>
                <p className="landing__para">
                  As a Frontend Web Developer, my goal is to develop visually
                  striking user interfaces that elevate the overall
                  functionality of websites and web applications.
                </p>
                <button className="landing__button">Projects</button>
              </div>
            </div>
          </div>
        </section>
        <section id="about">
          <div className="container">
            <div className="row">
              <div className="aboutus__title--wrapper">
                <h2 className="about__title">ABOUT ME</h2>
                <span className="line"></span>
                <p className="about__para">
                  I'm a frontend web developer who loves creating visually
                  stunning user interfaces. Explore my experience in designing
                  websites and applications, and my drive to improve my
                  programming and technology skills.
                </p>
              </div>
              <div className="aboutus__wrapper">
                <div className="aboutus__left">
                  <h3 className="aboutus__left--title">Get to know me!</h3>
                  <p className="aboutus__left--para">
                    As a frontend web developer, my goal is to build stunning
                    user interfaces that drive the success of websites and web
                    applications. Check out some of my projects to see my work
                    in action. I also enjoy sharing my web development knowledge
                    with others, so feel free to connect with me on LinkedIn
                    where I post useful content related to programming and web
                    development. I'm actively seeking job opportunities that
                    allow me to contribute, learn, and grow. If you have an
                    opportunity that matches my skills and experience, don't
                    hesitate to contact me.
                  </p>
                  <a href="#contact">
                    <button className="about__button">contact</button>
                  </a>
                </div>
                <div className="aboutus__right">
                  <h3 className="aboutus__right--title">My Skills</h3>
                  <div className="aboutus__skills--container">
                    <div className="skill">HTML</div>
                    <div className="skill">CSS</div>
                    <div className="skill">JavaScript</div>
                    <div className="skill">React</div>
                    <div className="skill">GIT</div>
                    <div className="skill">Github</div>
                    <div className="skill">Responsive Design</div>
                    <div className="skill">NextJS</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
